package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("UI Testing IU")
    void generatedTest() {
        step("Open https://informunity.ru/", () -> {
            step("// todo: just add selenium action");
        });

        step("Assert that icon logo is visible", () -> {
            step("// todo: just add selenium action");
        });

        step("click on \"Мы\"", () -> {
            step("// todo: just add selenium action");
        });

        step("assert that in url \"/about\"", () -> {
            step("// todo: just add selenium action");
        });

        step("click on \"Связаться с нами\"", () -> {
            step("// todo: just add selenium action");
        });

        step("make sure contact form is opened", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://informunity.ru/'", () ->
            open("https://informunity.ru/"));

        step("Page title should have text 'informUnity — партнер, опытный интегратор Bitrix24'", () -> {
            String expectedTitle = "informUnity — партнер, опытный интегратор Bitrix24";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://informunity.ru/'", () ->
            open("https://informunity.ru/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}